### PR TITLE
Alignment with zipline 1.1.4

### PR DESCRIPTION
**Pull request by peterfabakker**

### CODE REVIEW

**Comment by peterfabakker** [comment]
For the reviewers. 
I'm trading this branch for a month now without issues. 
The conda part needs probably dropping as it gives too much pain and not much gain

**Comment by tibkiss** [comment]
Please don't encapsulate other commits into yours, we should be cherry-picking these and shall not squash them into one.

**Comment by tibkiss** [comment]
Taking a look on the CI:
So many tests are failing on this branch that we cannot even get the count (Travis is cutting the output).

I do not recommend trading from this branch.

**Comment by tibkiss** [comment]
Please reopen a new PR when the problems are addressed: 
 - original authors retained
 - tests are passing.

Thank you.

**Pull request closed without merging**
