### PR TITLE
Fix history lookup in live

### PR DESCRIPTION
**Pull request by tibkiss**

### CODE REVIEW

**Comment by tibkiss** [comment]
This patch only changes the behavior in live trade. Without forcing the emission rate to minutely we'll rely on the underlying data bundle's emission rate (which is often not minutely). That is, with quandl we'll only be called twice a day (even though we have live data subscription). 

Unfortunately it is not possible to change the emission rate from the command line atm.

**Comment by bartosh** [comment]
I'm ok with forcing emission rate, but it shouldn't be done implicitly from my point of view. My concern was about removed check for data frequency.

**Comment by tibkiss** [comment]
@bartosh : Added back the data freq check

**Comment by tibkiss** [comment]
Noticed that an old, already merged change sneaked into this PR.
Closing this one and will post new one.

**Pull request closed without merging**
