### PR TITLE
Merge Quantopian's zipline/master branch to zipline-live/master

### PR DESCRIPTION
**Pull request by tibkiss**
This is the first step of moving live branch into master. 
Bringing zipline-live's master in sync with Quantopian's master.

### CODE REVIEW

**Comment by tibkiss** [comment]
Tests are failing due to PEP8 problems in `live_demo.py`:
https://travis-ci.org/zipline-live/zipline/jobs/238201764#L1174

@pbharrin : do you mind if I remove that file?

**Comment by pbharrin** [comment]
@tibkiss you can remove live_demo.py, it is no longer needed.

**Comment by tibkiss** [comment]
Thanks for merging, Ed!

**Comment by bartosh** [comment]
btw, are you going to rebase live branch the same way?

**Pull request merged**
