### PR TITLE
Merge latest changes from quantopian's zipline/master

### PR DESCRIPTION
**Pull request by amarin15**
The master branch is currently `113 commits ahead, 263 commits behind quantopian:master`. This merges the missing 263 commits from quantopian's master. The only files that I had to fix conflicts for were:
- `.travis.yml`
- `README.rst`
- `tests/resources/example_data.tar.gz`
- `zipline/__main__.py`
- `zipline/data/benchmarks.py`
- `zipline/data/loader.py`
- `zipline/resources/market_data/SPY_benchmark.csv`
- `zipline/utils/run_algo.py`

So when reviewing, you only really need to look at the changes in the files above and see if they make sense. I kept the zipline-live version of `README.rst` and quantopian version of `example_data.tar.gz` and `SPY_benchmark.csv`. If you want to see the merge commit, the GitHub UI displays all the changes it pulls in, but `git show 43a3bc` outputs only the merge conflicts that were fixed:  https://gist.github.com/alexukf/6cd8a7e031b2b78a331a9768b40f200c

### CODE REVIEW

**Comment by alexukf** [comment]
The error seems to be

```
======================================================================
ERROR: test suite for <class 'tests.test_examples.ExamplesTests'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/nose/suite.py", line 316, in 
setupContext
    try_run(context, names)
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/zipline-live/zipline/zipline/testing/fixtures.py", line 93, in setUpClass
    cls.init_class_fixtures()
  File "/home/travis/build/zipline-live/zipline/tests/test_examples.py", line 62, in init_class_fixtures
    'example_data/root/data/' + data
  File "/home/travis/build/zipline-live/zipline/zipline/utils/paths.py", line 75, in update_modified_time
    os.utime(path, times)
FileNotFoundError: [Errno 2] No such file or directory
```

Might be related to [this](https://github.com/zipline-live/zipline/pull/83/files#diff-49b2ecf603bdba3f0885ae9c95438a09R105) change

**Comment by alexukf** [comment]
The missing file is coming from their `example_data.tar.gz`, so I'll need to add that as well

**Comment by tibkiss** [comment]
Thanks for this contribution.

This is a moderately risky change given the amount of code change we introduce.
Did you run this code live with an algorithm? 
Normally I run my changes for one week in a Canary setup, before I push it into the repo. I'd appreciate if you could do the same here.

I'm wondering why we have the godzilla 'Rebase on top of quantopian/master' commit, if it is a rebase?

**Comment by tibkiss** [comment]
One more thing: to aid reviewing, could you please put your changes in the conflicting files into separate commits? Doing so might also remove the 'Rebase on top of quantopian/master' all-encompassing commit. Thanks!

**Comment by alexukf** [comment]
Hi @tibkiss, thanks for the review. The godzilla commit actually pulls in the missing 243 commits (including https://github.com/quantopian/zipline/commit/d7ef79779ecf6eb83cd77e65df10ec0cd9f8fa4e which you mentioned). If you look through the github UI, https://github.com/zipline-live/zipline/pull/83/commits/ee50d51f90baa4c89b7b379173f43a31b05366a9 will indeed show all the combined changes. But if you want to see only the merge conflicts I fixed, you can pull my branch and run 
- `git show ee50d51f` - this is my initial merge
- `git show 665f1488` - fixed a line I forgot to edit
- `git show 1251a457` - the missing file was from the `example_data.tar.gz` I initially didn't override, but then added quantopian's version

As much as I trust quantopian's commits, you're right that the merge should be tested on a live algo. Unfortunately I didn't get a chance to do that since I don't have an IB account yet. Will get to it in a while as well, but if someone else wants to test these changes on a dummy algo, please go ahead. Or better yet, they can try a merge/rebase themselves, as it doesn't take very long to do (only 8 conflicts).

**Comment by alexukf** [comment]
I merged all the latest changes from quantopian in a single commit. Unfortunately it's not possible to put the changes in the files with conflicts into separate commits (at least not trivially), since you can't commit with unresolved conflicts while doing a git merge. If you want to see the merge commit, the GitHub UI does indeed display all the changes it pulls in, but `git show 43a3bc` locally outputs only the merge conflicts that were fixed:  https://gist.github.com/alexukf/6cd8a7e031b2b78a331a9768b40f200c
An alternative would be to only look at the 8 (5 really) files that had conflicts in the PR (see new PR description).

Tested with `nosetests` locally, but did not test with a live algo yet. As you mentioned, this should probably be merged after it's tested with a live algo.

**Comment by tibkiss** [comment]
Thanks @alexukf , I'll try to review it next week.

**Comment by tibkiss** [comment]
@alexukf : Thanks for this work.   I'm afraid there is a misunderstanding here.

To achieve maintainable fork we need to avoid having large merge commits, such as the 'Merge latest quantopian changes' which encompasses 200+ changes into a single change. 

I'd suggest that you take https://github.com/zipline-live/zipline/pull/71 as an example, where the original author, commit message is retained.

Additionally, I'm just about to post a PR for https://github.com/zipline-live/zipline/issues/84 which will cause merge conflicts. I'd prefer to have that PR merged first for two reasons: 
a) it brings a new feature
b) it was extensively tested (using in production for two weeks now).

I'm happy to help executing and testing the rebase, but I'd recommend we sync up in chat to reduce the chance of further mis-communication. Thanks for your understanding.

**Comment by tibkiss** [comment]
This change became outdated. Closing.

**Pull request closed without merging**
