### PR TITLE
Live: Order support for IB Broker

### PR DESCRIPTION
**Pull request by tibkiss**
The following functions are implemented: order (market, limit, stop & stop limit), cancel_order, get_order, get_open_orders. Testing was done manually since it is pointless to mock out the whole tws & check simple wiring code.

### CODE REVIEW

**Comment by tibkiss** [comment]
Two errors:
 - IbPy2 dependency is not processed in Travis / AppVeyor
 - Treasury download error, see: https://github.com/quantopian/zipline/issues/1817

**Comment by bartosh** [comment]
Interesting. Why tests didn't fail on PR #19 and #12 ?

**Comment by pbharrin** [comment]
@bartosh It looks like that treasuries URL stopped working ~13hours ago.  So PR #19, and PR #12 probably would have the same error if they were submitted today.

**Comment by pbharrin** [comment]
Both the Python 2.7 and 3.4 builds have [an error](https://travis-ci.org/zipline-live/zipline/jobs/236311060#L778): 
`No module named ib.ext.EClientSocket`
[Here](https://travis-ci.org/zipline-live/zipline/jobs/236311060#L2932) is the full stack trace.  

PR #12 moving IB to etc/requirements_live_ib.txt caused this.  I will add etc/requirements_live_ib.txt to .travis.yml to fix.

**Comment by bartosh** [comment]
Guys, let's agree not moving PRs until we fix tests. I takes much more time to fix broken target branch than to avoid breaking it.

**Comment by bartosh** [comment]
> PR #12 moving IB to etc/requirements_live_ib.txt caused this. I will add etc/requirements_live_ib.txt to .travis.yml to fix.

PR #12 passed all tests as far as I can see. how come it broke this one?

**Comment by tibkiss** [comment]
@pbharrin : May I ask to not to merge PRs which are failing during test? 
It is easier to get the broken build fix in the offending PR. Thanks!

**Comment by tibkiss** [comment]
@pbharrin : Sorry, I missed that you hotfixed the PR. Please ignore my previous comment. 🤐

**Pull request merged**
