### PR TITLE
Test fixes caused by Live Broker PR

### PR DESCRIPTION
**Pull request by tibkiss**

### CODE REVIEW

**Comment by tibkiss** [comment]
Please hold on with the merge, I need to fix the Python3 related issues first.

**Comment by tibkiss** [comment]
Finally a semi-green build. The failing testcases (test_examples under Python3 @ Travis) are likely related to the ^GSPC -> SPY change. I'm not sure how to fix the missing ibpy2 package under appveyor (and I'm not so motivated to fix the problems for windows platform....)

@bartosh  / @pbharrin  : Could you please review this PR?

**Comment by bartosh** [comment]
Great work! Thank you for fixing this!

Hmm, I should've run python3 tests. Remaining issues look like unicode and python3 specific ones.

Will look at them tomorrow.

We need to fix all failures, including windows ones I believe.

**Comment by pbharrin** [comment]
The error appears to be Python 3 reading a pickle that was written in Python 2.  
See [this post](https://stackoverflow.com/questions/11305790/pickle-incompatability-of-numpy-arrays-between-python-2-and-3).  

This is happening with the different example algorithms: olmar, buyapple, etc.  

I think this stems from creating new algo results for the new benchmark SPY.  We should figure out how to create the tests/resources/example_data.tar.gz without creating this issue.

**Comment by pbharrin** [comment]
Here is a link to the Pickle library section on data formats perhaps setting this when creating example_data.tar.gz will solve this problem.  
https://docs.python.org/3.4/library/pickle.html#data-stream-format

**Comment by tibkiss** [comment]
It makes me wonder how is this problem not present in quantopian's zipline?

**Comment by pbharrin** [comment]
@bartosh How was this file created?

**Comment by bartosh** [comment]
I think the problem can be solved by running tests/resources/rebuild_example_data from python3. It will use pickle:2 serialization which should work for both python versions.

**Pull request merged**
